name: borisbaranov
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39235
title: Борис Баранов
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5e6e8'
    - '#b2b4b3'
    - '#070506'
    - '#b54a22'
    - '#6a6458'
  brandStrength: 0
  lightness: 0.794245790457353
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
