name: borisbaranov
favicon: null
layout_spectrum: 0.9472607581410557
typography_spectrum: 0.1045788680203259
title: Борис Баранов
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7dbdc'
    - '#9c9791'
    - '#090504'
    - '#975231'
    - '#611e0a'
  brandStrength: 0
  lightness: 0.794245790457353
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
